/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TRANSLATIONS = {
  en: {
    title: "NammaInfra AI",
    subtitle: "Civic Operating System of Tamil Nadu",
    tagline: "High-Performance GovTech Portal",
    tamilNaduGovt: "GOVERNMENT OF TAMIL NADU",
    motto: "Truth Alone Triumphs • வாய்மையே வெல்லும்",
    citizenTab: "Citizen Portal",
    officialTab: "Official Command Center",
    reportIssueTitle: "Quick Report Civic Issue",
    reportIssueDesc: "Report street issues instantly. Our AI system will classify, score severity, and route to the correct municipal ward in real-time.",
    fullName: "Full Name",
    phone: "Mobile Number",
    descriptionPlaceholder: "E.g. Large pothole near the bus stop, overflowing drain water block, broken streetlight...",
    descriptionLabel: "Describe the Issue",
    getGeoLocation: "Detect GPS Location",
    gpsDetected: "GPS Detected",
    latitude: "Latitude",
    longitude: "Longitude",
    imageSimTitle: "Attach Issue Photo (Optional)",
    imageSimDesc: "Drag & drop or snap to upload a photo for AI analysis",
    submitReport: "Initialize AI Dispatch & Route",
    processingAI: "AI Engine analyzing core issue...",
    successReport: "Issue Dispatched Successfully!",
    activeComplaints: "Your Submitted Issues",
    noActiveComplaints: "You haven't reported any issues yet.",
    statusPending: "Pending Review",
    statusInProgress: "Restoration In Progress",
    statusResolved: "Resolved & Closed",
    resolvedTime: "Resolved at",
    severityLevel: "Severity",
    wardRoute: "Routed to",
    actionPlan: "Recommended Actions",
    expectedResolution: "SLA Resolution Target",
    hours: "hours",
    beforeAfterTitle: "Before / After Verified Closure",
    before: "Before",
    after: "After",
    statsTotalCount: "Total Alerts",
    statsPendingCount: "Awaiting Action",
    statsInProgCount: "Active Restoration",
    statsResolvedCount: "Resolved Issues",
    avgResolution: "Avg Resolution SLA",
    leaderboardTitle: "Ward Performance Leaderboard",
    leaderboardDesc: "Real-time government efficiency tracking by administrative zones.",
    topPerformingWards: "Top Performing Wards",
    wardScore: "Score",
    wardAvgSLA: "Avg SLA",
    complaintsText: "Complaints",
    viewOnMap: "Locate Pin",
    mapViewTitle: "Live Operations Geospatial Map",
    mapViewSubtitle: "Interactive Tamil Nadu Municipal Wards Grid",
    selectComplaintMap: "Select an active marker to check dispatch logs and operations review.",
    updateStatusLabel: "Command Actions",
    markInProg: "Authorize Work Crew (In-Progress)",
    markResolved: "Verify & Close Incident (Resolved)",
    officialRemarksPlaceholder: "Enter work crew resolution report and structural closure details...",
    remarks: "Remarks",
    saveResolution: "Authenticate Incident Closure",
    searchPlaceholder: "Filter issues by id, type or ward..."
  },
  ta: {
    title: "நம்மஇன்ஃப்ரா AI",
    subtitle: "தமிழ்நாடு குடிமை இயக்க முறைமை",
    tagline: "உயர் செயல்திறன் கொண்ட அரசுத் தொழில்நுட்ப போர்டல்",
    tamilNaduGovt: "தமிழ்நாடு அரசு",
    motto: "வாய்மையே வெல்லும்",
    citizenTab: "பொதுமக்கள் போர்டல்",
    officialTab: "அதிகாரிகள் கட்டுப்பாட்டு மையம்",
    reportIssueTitle: "குடிமைப் பிரச்சனையை விரைவாகப் புகாரளிக்கவும்",
    reportIssueDesc: "தெருப் பிரச்சனைகளை உடனடியாகப் புகாரளிக்கவும். எங்களின் AI தொழில்நுட்பம் புகாரை வகைப்படுத்தி, தீவிரத்தன்மையை மதிப்பிட்டு, உண்மையான நேரத்தில் சரியான நகராட்சி வார்டுக்கு வழிநடத்தும்.",
    fullName: "முழு பெயர்",
    phone: "அலைபேசி எண்",
    descriptionPlaceholder: "உதாரணமாக: பஸ் ஸ்டாப் அருகே பெரிய பள்ளம், சாக்கடை நீர் அடைப்பு, உடைந்த தெருவிளக்கு...",
    descriptionLabel: "பிரச்சனையைப் பற்றி எழுதுக",
    getGeoLocation: "ஜிபிஎஸ் இருப்பிடத்தைக் கண்டறி",
    gpsDetected: "ஜிபிஎஸ் கண்டறியப்பட்டது",
    latitude: "அட்சரேகை (Lat)",
    longitude: "தீர்க்கரேகை (Lng)",
    imageSimTitle: "பிரச்சனைப் புகைப்படத்தை இணைக்கவும் (விருப்பத்திற்குரியது)",
    imageSimDesc: "AI பகுப்பாய்வுக்காக ஒரு புகைப்படத்தை இழுத்து விடவும் அல்லது பதிவேற்றவும்",
    submitReport: "AI பகுப்பாய்வை தொடங்கி புகாரளி",
    processingAI: "AI தொழில்நுட்பம் மூலம் பகுப்பாய்வு செய்யப்படுகிறது...",
    successReport: "புகார் வெற்றிகரமாக வார்டுக்கு அனுப்பப்பட்டது!",
    activeComplaints: "உங்கள் சமர்ப்பிக்கப்பட்ட புகார்கள்",
    noActiveComplaints: "நீங்கள் இன்னும் எந்த புகாரையும் சமர்ப்பிக்கவில்லை.",
    statusPending: "மதிப்பாய்வில் உள்ளது",
    statusInProgress: "மறுசீரமைப்பு வேலையில் உள்ளது",
    statusResolved: "தீர்வு காணப்பட்டு மூடப்பட்டது",
    resolvedTime: "தீர்க்கப்பட்ட நேரம்",
    severityLevel: "தீவிரம்",
    wardRoute: "அனுப்பப்பட்ட வார்டு",
    actionPlan: "பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்",
    expectedResolution: "மதிப்பிடப்பட்ட தீர்வு காலம்",
    hours: "மணிநேரம்",
    beforeAfterTitle: "முன்பு / பின்பு சரிபார்க்கப்பட்ட அறிக்கை",
    before: "புகாரின் போது",
    after: "தீர்வுக்குப் பின்",
    statsTotalCount: "மொத்த புகார்கள்",
    statsPendingCount: "மதிப்பாய்வில் உள்ளவை",
    statsInProgCount: "வேலையில் உள்ளவை",
    statsResolvedCount: "தீர்க்கப்பட்ட புகார்கள்",
    avgResolution: "சராசரி தீர்வு காலம்",
    leaderboardTitle: "வார்டு செயல்திறன் தரவரிசை",
    leaderboardDesc: "நிர்வாக மண்டலங்களின்படி நிகழ்நேர அரசாங்க செயல்திறன் கண்காணிப்பு.",
    topPerformingWards: "சிறப்பாகச் செயல்படும் வார்டுகள்",
    wardScore: "மதிப்பெண்",
    wardAvgSLA: "சராசரி காலம்",
    complaintsText: "புகார்கள்",
    viewOnMap: "வரைபடத்தில் காட்டு",
    mapViewTitle: "நிகழ்நேர புவிசார் வரைபடம்",
    mapViewSubtitle: "தமிழ்நாடு நகராட்சி வார்டுகள் ஊடாடும் வரைபடம்",
    selectComplaintMap: "வழக்கு அறிக்கைகள் மற்றும் செயல்பாட்டு பதிவுகளை சரிபார்க்க வரைபடத்தில் உள்ள குறியீட்டைத் தேர்ந்தெடுக்கவும்.",
    updateStatusLabel: "கட்டளை நடவடிக்கைகள்",
    markInProg: "பணியாளர்களை அங்கீகரி (செயல்பாட்டில் உள்ளது)",
    markResolved: "சம்பவத்தை சரிபார்த்து முடிவு செய் (தீர்க்கப்பட்டது)",
    officialRemarksPlaceholder: "பணியாளர்களின் தீர்வு அறிக்கை மற்றும் கட்டமைப்பு விவரங்களை உள்ளிடவும்...",
    remarks: "விவரக்குறிப்பு",
    saveResolution: "சம்பவக் கோப்பை மூடுவதை உறுதிசெய்",
    searchPlaceholder: "புகார்களை ஐடி, வகை அல்லது வார்டு மூலம் தேடுக..."
  }
};
